### PR TITLE
Updating React to v16.12.0

### PR DESCRIPTION
**Pull request by kgorski-quizlet**
Replaces React 16.2.0 (November 28, 2017) with 16.12.0 (November 14, 2019), just like we use in prod

### CODE REVIEW

**Comment by eviechan** [comment]
I'll test this later today to ensure that the app still runs as expected with the updated version. Thanks for doing this, @kgorski-quizlet !

**Review by eviechan — COMMENTED** [review]
Just set it up on my local, LGTM with one caveat, the user has to be between node 6 and node 8, otherwise running `yarn install` or `npm install` will fail because of dependency mismatch. Do you mind going ahead and updating the README to put that caveat in for now, or if you're feeling up to it, we can also update all of our `devDependencies` to work properly with any version greater than node 6?

**Comment by kgorski-quizlet** [comment]
@eviechan I updated the dependencies to more recent versions and tested on node 6/8/12 and 6 was the only version that still had trouble, so I updated the README to recommend 8+ as we do for the Angular starter.

**Review by eviechan — APPROVED** [review]
Thanks for doing this! Just tested out the updates on node 13 and looks great. Feel free to merge 👍

**Pull request merged**
