### PR TITLE
Angular 1 scaffold

### PR DESCRIPTION
**Pull request by eviechan**
Creating Angular 1 `LearnMode` scaffold for candidates.

### CODE REVIEW

**Review by quizlet-chiragmedhora — COMMENTED** [review]
Thank you for putting this together, Evelyn! Just one comment: could you please add a readme file, similar to the ones we have for React and vanilla? Eg. https://github.com/guizlet/frontend-interview/blob/master/vanilla-js/README.md

**Comment by eviechan** [comment]
Will definitely do, it was the last thing on my list of todos :)

**Comment by eviechan** [comment]
@quizlet-chiragmedhora added readme file. Let me know if you can set up the app with the provided instructions!

**Comment by quizlet-chiragmedhora** [comment]
Thanks for adding the readme. I tried to run the app, but got this:
```
> parcel src/index.html

module.js:471
    throw err;
    ^

Error: Cannot find module '../lib/cli'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/interview/frontend-interview/angular/angular-1/node_modules/parcel-bundler/bin/cli.js:6:7)
```

**Review by quizlet-chiragmedhora — APPROVED** [review]

**Pull request merged**
